### ISSUE TITLE
AMQP.Queue.declare takes some time

### ISSUE THREAD

**Issue by kuffel** [pma/amqp#102]
On some of our systems (mostly slower machines) we see a strange behavior of AMQP.Queue.declare, it looks like it takes too long and when we publish the message it is gone because the queue seems to be not there. So the message just disappears. 

Simple example on how to reproduce the issue:

```elixir
defmodule Test do
  @moduledoc false

  # In mixfile: {:amqp, "~> 1.0.2"}
  # Erlang 20.3.6
  # RabbitMQ 3.7.4
  # Elixir 1.6.1

  def demo() do
    {:ok, connection} = AMQP.Connection.open()
    {:ok, channel} = AMQP.Channel.open(connection)

    # Make sure the channel and the exchange are not already there
    AMQP.Exchange.delete(channel, "DEMO")
    AMQP.Queue.delete(channel, "Q1")

    # Create exchange, declare queue, bind the queue.
    :ok = AMQP.Exchange.topic(channel, "DEMO")
    {:ok, _map} = AMQP.Queue.declare(channel, "Q1")
    # Process.sleep(1_000)  # Putting a sleep in here fixes the problem
    :ok = AMQP.Queue.bind(channel, "Q1", "DEMO")
    AMQP.Basic.publish(channel, "DEMO", "", "Hello Q1")
    # Sometimes the message is not in the queue
  end

end
```

As said this only happens on slower machines and only sometimes. Does someone have an explanation for that?

**Comment by ono** [comment]
It's bit complicated and misleading but `AMQP.Basic.publish` is actually an async operation [*1]. It might be a good idea to do something on amqp layer but I haven't had enough time to think it properly.

My best guess is that the process exits right after you call `AMQP.Basic.publish`. In that case, the process might have shut down before the message is sent. I suggest you to try [AMQP.Confirm](https://hexdocs.pm/amqp/AMQP.Confirm.html) module and make sure all messages have been published before process is shut down.

See also http://www.rabbitmq.com/confirms.html#publisher-confirms

[*1] https://www.rabbitmq.com/releases/rabbitmq-erlang-client/v2.1.0/doc/amqp_channel.html#call-3
