### ISSUE TITLE
Being sure that a message sent with Basic.publish is really sent.

### ISSUE THREAD

**Issue by Ciboulette** [pma/amqp#104]
Hello Everybody, 

I would like to be completely sure that a message is sent or throw an exception if there is a connection issue.

I have set up a stable connection with a 10sec heartbeat. I am testing my system and it happens that if i cut the wifi (just to test a network problem) and i try sending message with 
```
  Basic.publish(channel, "", queue, payload, persistent: true, mandatory: true)
``` 
this method returns `:ok`, the message is not really sent because there is a network issue and the connection problem callback happens 20sec later. So if my understanding is correct, there is a 20sec window where my messages are lost. Any idea how i can handle this case? 

Thanks a lot

**Comment by Ciboulette** [comment]
Thanks @pma. From my understanding, by using`AMQP.Confirm.wait_for_confirms_or_die/2`, message cannot be queued and must consume by the consumer immediately?

**Comment by pma** [comment]
@Ciboulette No. `AMQP.Confirm.wait_for_confirms*` will be a confirmation that the RabbitMQ broker received your message and sent it through an Exchange. It provides no guarantee that a consumer already consumed it. So it can be queued.

**Comment by Ciboulette** [comment]
@pma ok thanks. Last question `:amqp_channel.register_confirm_handler/2` send confirm msg like `{:"basic.ack", something, bool}` do you know what represent something and bool?

**Comment by Ciboulette** [comment]
And to show you, about my thoughts on `AMQP.Confirm.wait_for_confirms*`, in the docs it's written:
```
 @doc """
  Wait until all messages published since the last call have been
  either ack'd or nack'd by the broker, or until timeout elapses.
  If any of the messages were nack'd, the calling process dies.
  """
```

**Comment by pma** [comment]
@Ciboulette Regarding the first question, it's the Erlang record described here (http://www.rabbitmq.com/amqp-0-9-1-quickref.html). An Erlang record is internally represented as a tuple where the first element is the type of record. The remaining two are therefore the delivery_tag, and the multiple flag.

Regarding the second, I think you're initial assumption just ignored the key word **broker** in the sentence "either ack'd or nack'd by the broker". The RabbitMQ also sends acks, nacks back to the publisher, which are separate from the dialog between broker and consumer.
