### ISSUE TITLE
Lost connections on publisher?

### ISSUE THREAD

**Issue by damien-roche** [pma/amqp#105]
I noticed in the examples there was a retry mechanism in case of connection drop, but it was only on the consumer (?).

I currently have a very simple publisher which calls basic send. Everything works great.. but I left my Elixir client running for the last couple of days, came back and attempted to send a message and received this:

```
00:58:15.838 [error] GenServer :rmq_publisher terminating
** (stop) exited in: :gen_server.call(#PID<0.942.0>, {:call, {:"basic.publish", 0, "checks_exchange", "", false, false}, {:amqp_msg, {:P_basic, :undefined, :undefined, :undefined, 1, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined}, "{'url':'google.com'}"}, #PID<0.929.0>}, 60000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

Have also noticed these errors intermittently, though quite rare. 

The connection in RMQ shows a heartbeat.

![rabbitmq management 1](https://user-images.githubusercontent.com/652266/43994772-8fcab406-9dcc-11e8-855f-db9f44c9156c.png)

However, after a couple of days both connections for my Elixir publisher and a consumer had dropped. My consumer is written in Go so I doubt this is entirely related to the lib, would just appreciate some advice.

Should I do as in the examples and build a retry mechanism into the publisher? Or is this perhaps a known issue and amqp has support already (but requires certain config, etc)?

Thanks.

**Comment by ono** [comment]
Connection can drop in various reasons. I have updated [README](https://github.com/pma/amqp/blob/master/README.md#stable-rabbitmq-connection). I hope it helps you to implement the reconnection logic.

If you have a long open channel, you might want to consider implementing similar logic for that too. I'd suggest you to start to open/close a channel for each publish at the beginning. Then consider performance tuning by needs.
