### ISSUE TITLE
Could not compile dependency :lager with {:amqp, "~> 1.0"}

### ISSUE THREAD

**Issue by Ciboulette** [pma/amqp#114]
Hey all!

My setup is 👇
```
$ elixir -v
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.6 (compiled with OTP 19)
```

The error is 👇when I run `mix compile`
```elixir
** (Mix) Could not compile dependency :lager, "/Users/louiscibot/.asdf/installs/elixir/1.6.6/.mix/rebar3 bare compile --paths "/Users/louiscibot/zenaton/hoover/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile lager", update it with "mix deps.update lager" or clean it with "mix deps.clean lager"
```

Help is welcomed 🙏

**Comment by derekstavis** [comment]
I have been testing this fork and it seems to solve the issue:

https://github.com/kmussel/amqp/tree/v1.0.4

It appears to me that this forks fix this issue as a side-effect of updating lager version.

**Comment by ono** [comment]
@Ciboulette I am not sure if that's related but OTP versions are different between runtime and compile. Can you try compiling Elixir with OTP 20 and see how it works? If it doesn't help, can you upload an example project with a precise information to reproduce the error?

@derekstavis I think it's related to [OTP 21 issue](https://github.com/pma/amqp/issues/99) but thanks for sharing!

**Comment by ono** [comment]
Closing this. Feel free to reopen with the information I requested above.
