### ISSUE TITLE
Syntax flaw in documentation of `ssl_options`

### ISSUE THREAD

**Issue by Qqwy** [pma/amqp#115]
https://github.com/pma/amqp/blob/42d2075a9a88a94e493b97106c14dde6c5f204c3/lib/amqp/connection.ex#L36

This should be "defaults to `:none`" for clarity that we are talking about the atom here.

**Comment by ono** [comment]
Good spot 👍 Thanks!

https://github.com/pma/amqp/commit/62b384b7818c632db21afd92609f7e9aab755b1d
