### ISSUE TITLE
Intermittent ** (EXIT) time out instead of {:error, :econnrefused} or {:error, :timeout}

### ISSUE THREAD

**Issue by pyramind10** [pma/amqp#119]
`AMQP.Connection.open` intermittently exits after 60 seconds. 

I would expect to receive `{:error, :timeout}` or `{:error, :econnrefused}`. 95% of the time the response is `{:error, :econnrefused}`.

It looks like the default [connection_timeout](https://github.com/rabbitmq/rabbitmq-erlang-client/blob/c6a763d5482d455e7129b438def60dced69f8abb/include/amqp_client_internal.hrl#L39) is the same as the [rabbitmq-erlang-client gen_server_call_timeout default](https://github.com/rabbitmq/rabbitmq-erlang-client/blob/c6a763d5482d455e7129b438def60dced69f8abb/include/amqp_client_internal.hrl#L39). They are both set to 60000, therefore the genserver exits causing the "stable" connection to fail without retry. 

When using a connection loop such as

```elixir
defp rabbitmq_connect do
    case Connection.open(host: "rabbitmq") do
      {:ok, conn} ->
        Process.monitor(conn.pid)
        {:ok, conn}

      {:error, _} ->
        :timer.sleep(1000)
        rabbitmq_connect()
    end
  end
```

It makes it impossible to catch the error case `{:error, :timeout}`. I think it would be more user friendly to default the connection timeout to something less that 60000. ie. 50000, 45000, 30000. This way there is no need to trap exits for timeouts. I feel 30000 is sufficient.

Exit BAD
```bash
iex(35)> AMQP.Connection.open(host: "rabbitmq")
iex(30)>
09:51:23.737 [info]  [supervisor: {#PID<0.569.0>, :amqp_connection_sup}, started: [pid: #PID<0.570.0>, name: :connection_type_sup, mfargs: {:amqp_connection_type_sup, :start_link, []}, restart_type: :transient, shutdown: :infinity, child_type: :supervisor]]

09:51:23.737 [info]  [supervisor: {#PID<0.569.0>, :amqp_connection_sup}, started: [pid: #PID<0.571.0>, name: :connection, mfargs: {:amqp_gen_connection, :start_link, [#PID<0.570.0>, {:amqp_params_network, "guest", "guest", "/", 'rabbitmq', 5672, 0, 0, 10, 60000, :none, [&:amqp_auth_mechanisms.plain/3, &:amqp_auth_mechanisms.amqplain/3], [], []}]}, restart_type: :intrinsic, shutdown: :brutal_kill, child_type: :worker]]
** (exit) exited in: :gen_server.call(#PID<0.571.0>, :connect, 60000)
    ** (EXIT) time out
    (stdlib) gen_server.erl:223: :gen_server.call/3
    (amqp) lib/amqp/connection.ex:116: AMQP.Connection.do_open/1

```
Tuple GOOD
```bash
iex(216)> AMQP.Connection.open(host: "rabbitmq", connection_timeout: 30000)

10:42:35.474 [info]  [supervisor: {#PID<0.1209.0>, :amqp_connection_sup}, started: [pid: #PID<0.1210.0>, name: :connection_type_sup, mfargs: {:amqp_connection_type_sup, :start_link, []}, restart_type: :transient, shutdown: :infinity, child_type: :supervisor]]

10:42:35.474 [info]  [supervisor: {#PID<0.1209.0>, :amqp_connection_sup}, started: [pid: #PID<0.1211.0>, name: :connection, mfargs: {:amqp_gen_connection, :start_link, [#PID<0.1210.0>, {:amqp_params_network, "guest", "guest", "/", 'rabbitmq', 5672, 0, 0, 10, 30000, :none, [&:amqp_auth_mechanisms.plain/3, &:amqp_auth_mechanisms.amqplain/3], [], []}]}, restart_type: :intrinsic, shutdown: :brutal_kill, child_type: :worker]]
{:error, :timeout}
```

All that being said the ability to set `connection_timeout` is there and works as expected 👍 . This is more about setting a friendly default. I make this suggestion because the `** (EXIT) time out` is not consistent and it's catastrophic. By setting the default `connection_timeout` to something less than 60000 we get consistent default responses from the `AMQP.Connection.open` function that won't crash our connection processes. 

```elixir
defp rabbitmq_connect do
    case Connection.open(host: "rabbitmq") do
      {:ok, conn} ->
        Process.monitor(conn.pid)
        {:ok, conn}
      {:error, :timeout} ->
        # Do timeout stuff
      {:error, _} ->
        :timer.sleep(1000)
        rabbitmq_connect()
    end
  end
```

**Comment by ono** [comment]
Thanks for reporting. I really appreciate the way you explain. I changed the default value to 50 seconds in master. Will bump the version soon.
