### ISSUE TITLE
Not supporting AMQP v1.0 and ActiveMQ

### ISSUE THREAD

**Issue by coby-spotim** [pma/amqp#121]
I'm attempting to create a consumer on an ActiveMQ queue (AWS Managed Queues).

When running `AMQP.Connection.open("amqp://@localhost:5672")`, I receive the following error: `{:error, {:server_sent_malformed_header, <<65, 77, 81, 80, 3, 1, 0>>}}`.

After checking in the logs of the ActiveMQ server, I see the following output:

```
WARN | Connection attempt from non AMQP v1.0 client. AMQP,0,0,9,1
WARN | Transport Connection to: tcp://172.18.0.1:57760 failed: org.apache.activemq.transport.amqp.AmqpProtocolException: Connection from client usingunsupported AMQP attempted
```

It seems like the current amqp client that is being used is below 1.0, which means we can't create consumers on ActiveMQ queues.

**Comment by coby-spotim** [comment]
@arpunk Thanks! Could you provide a quick example of how to utilize the raw library?

**Comment by vumanhcuongit** [comment]
do you have any plans to support it in near future?

**Comment by ono** [comment]
@vumanhcuongit We don't have any plan to support 1.0 at the moment. Our main aim here (at least for now) is to provide a thin wrapper around [amqp_client](https://hex.pm/packages/amqp_client) for Elixir programmers.

I keep this issue open as I think we should mention it on README.

**Comment by vumanhcuongit** [comment]
@ono thanks for your info 👍

**Comment by ono** [comment]
Added the information to README: https://github.com/pma/amqp/blob/master/README.md#does-the-library-support-amqp-10

Thanks!
