### ISSUE TITLE
Several rabbitmq hosts. How to connect?

### ISSUE THREAD

**Issue by Houdini** [pma/amqp#135]
Hello, I checked code for connection. It doesn't support connection to several amqp hosts, only to one.
However usually we run cluster of rabbitmq. But I have no idea how to connect to cluster.

Could you please with that?

**Comment by ono** [comment]
Sure.

```elixir
{:ok, conn1} = AMQP.Connection.open("amqp://host1")
{:ok, conn2} = AMQP.Connection.open("amqp://host2")
```

If you want to use [this example](https://github.com/pma/amqp#stable-rabbitmq-connection), you might want to change it to take an argument for host instead of `@host` module attribute.

Hope it helps!
