### ISSUE TITLE
Version 1.2.x should be 2.x?

### ISSUE THREAD

**Issue by mroach** [pma/amqp#138]
Is this library meant to follow [semantic versioning]?

If so, I believe the 1.2.x versions should be 2.x. For any application that was expecting `{:error, reason}` when a channel was closed, they're now seeing a process exit instead which of course has to be handled differently. This was introduced in #131 and the change in behaviour is outlined in the [basic_test.exs changes]

Since 1.2 breaks backwards compatibility with 1.1, following semantic versioning, shouldn't this release branch be 2.x and have a migration guide?

[semantic versioning]: https://semver.org/
[basic_test.exs changes]: https://github.com/pma/amqp/pull/131/files#diff-e639c318e338c6b5ffc5864d0d57d1e9

**Comment by ono** [comment]
Sorry for the late reply - I just came back from a vacation.

As [the commit message](https://github.com/pma/amqp/commit/cffb412fbd468d271d98a47c127f5bd3878384cc) suggests, the test actually never worked. The test exits before the process including the assertion spawned. If you check out `v1.1.1` and add `:timer.sleep(100)` after the spawn line, you see the actual behaviour. The change is not introduced by `v1.2.x` and we are trying to follow semver's practice.

Feel free to reopen the issue if you have further questions. Thanks!
