### ISSUE TITLE
Why is Confirm.wait_for_confirms/1 crashing my process?

### ISSUE THREAD

**Issue by gernotkogler** [pma/amqp#140]
First of all, thanks a lot for this library! Made my life a lot easier.

I'm using Confirm to catch non-existing exchange names when publishing a message. I would have expected that Confirm.wait_for_confirms/1 returns {:ok} on sucess and {:error, err} on failure. From my understanding the name of an elixir function that raises exceptions should end with a bang.

Furthermore, Confirm.wait_for_confirms/1 and Confirm.wait_for_confirms_and_die/1 behave exactly the same in my case. Both crash the process when publishing to a non-existing exchange.

Woudn't it be nice to

- implement Confirm.wait_for_confirms/1 returning {:ok} or {:error, err}, catching and forwarding Exceptions from amqp_client
- rename Confirm.wait_for_confirms_and_die/1 to Confirm.wait_for_confirms!/1

What do you think?

**Comment by ono** [comment]
> From my understanding the name of an elixir function that raises exceptions should end with a bang.

The bang function would raise an exception for the error non-bang function would handle. Non bang doesn't mean it's exception free. For example, `Ecto.Repo.insert` would return an error for validation. However it still raises an exception for a connection error.

Please refer [amqp_client document](https://www.rabbitmq.com/releases/rabbitmq-erlang-client/v2.8.3/doc/amqp_channel.html#wait_for_confirms_or_die-2) how it differs from `wait_for_confirms`.

You are making a good point on the potential improvements with bang/non-bang though. I feel that it might be good to handle some exceptions from Erlang library in this library. However the primary objective of this library is to provide a thin wrapper around Erlang library for Elixir developer. We don't plan to change the API right now but will consider when we do.
