### ISSUE TITLE
Compatibilities for newer versions (wiki)

### ISSUE THREAD

**Issue by dideler** [pma/amqp#142]
Hey @ono, the [Versions and Compatibilities](https://github.com/pma/amqp/wiki/Versions-and-Compatibilities) page was last updated on Nov 27, 2018 for 1.1.x.

What are the versions and compatibilities for 1.2.x?

**Comment by ono** [comment]
Good spot. Just updated the wiki. Thanks!

**Comment by nietaki** [comment]
@ono Does that mean `amqp` is not compatible with RabbitMQ 3.7.10 and lower? Or just untested?

**Comment by nietaki** [comment]
Sorry, I just read the inscription on the [Versions and Compatibilities](https://github.com/pma/amqp/wiki/Versions-and-Compatibilities) page, which clarifies it a bit, feel free to ignore me.

**Comment by ono** [comment]
No problems. Yeah, just untested.

It's a good idea to align a client version with server version. However, in reality, you have higher client version against the server version and it'd normally work without any issue.
