### ISSUE TITLE
Queue declaration with default exchange

### ISSUE THREAD

**Issue by victorprs** [pma/amqp#149]
Looking at the [rabbitmq tutorials](https://www.rabbitmq.com/tutorials/amqp-concepts.html), there is no need to declare a queue with the default params:

> The default exchange is a direct exchange with no name (empty string) pre-declared by the broker. It has one special property that makes it very useful for simple applications: every queue that is created is automatically bound to it with a routing key which is the same as the queue name.

Given that the declaration of the default exchange is automatic, every time that I try to declare the default exchange it gives an error. 

Solution:
It is possible to guarantee that exchange is not empty and I'm thinking it would improve the lib. What do you think?

**Comment by ono** [comment]
Hi @victorprs. I need bit more explanation on your suggestion. Which module and function are you proposing to update? And can you compare the proposed outcome with the current one?

Thanks!

**Comment by whatyouhide** [comment]
Also @victorprs, you are guaranteed that the default exchange is there, it's just part of the RabbitMQ API (same way you're guaranteed that there's a `queue.bind` method for example).
