### ISSUE TITLE
Upstream 'rabbitmq-erlang-client' dependency leaking credentials to logged output

### ISSUE THREAD

**Issue by YannickMeeus** [pma/amqp#153]
Hi all,

We've been building out a service using this library. When auditing the logs, we noticed that we're seeing RabbitMQ credentials being logged in plain text.

After some digging we found a closed issue in the upstream [rabbitmq-erlang-client](https://github.com/rabbitmq/rabbitmq-erlang-client) library,  addressed by [this Pull Request](https://github.com/rabbitmq/rabbitmq-erlang-client/pull/124) specifically.

The maintainers did state that they backported this fix to 3.7.x, but it's still present when using this elixir wrapper, which is currently dependant on: 

```
 {:amqp_client, "~> 3.7.11"},
```

What would be the process in getting the upstream, fixed dependency tested and referenced correctly in this library, as this is kinda a showstopper for us at the moment?

**Comment by ono** [comment]
`mix deps.update amqp_client` doesn't work?

**Comment by YannickMeeus** [comment]
`amqp_client` is not an explicit dependency in our project. Is the idiomatic way of forcing an upstream dependency to a specific version to have the upstream dependency *as* a project dependency and pin the version?

(I'm betraying my lack of experience in elixir and the whole associated stack here 😊)

**Comment by ono** [comment]
We like to provide a flexibility of a choice of the client version as much as possible. Server and client versions of RabbitMQ always get updated at the same time. The users of this library might want to use the client version which matches with the server version. We don't want to force the user to update the client to the specific version.

I personally never experienced any issues with the newer patched client version though. For example, if your RabbitMQ server version is `3.7.11` and you update the client to `3.7.19`, it will normally work. However we usually want to leave the choice to our users.

**Comment by YannickMeeus** [comment]
Right, I think I get your point now, and have made the changes on my end.
I'll still test them but I don't think there's anything more to add here.

Thanks ever so much for your help!

**Comment by thiagogsr** [comment]
hey guys, I still can't use the newest `amqp_client@3.7x` version since it is hard coded in `amqp` dependencies, how do you fix this?
