### ISSUE TITLE
RabbitMQ 3.8.0 support

### ISSUE THREAD

**Issue by ono** [pma/amqp#154]
Test amqp with the latest Erlang client: https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.0 and update mix.exs.

Note that 3.7.x client is still compatible with 3.8.x server.

**Comment by ono** [comment]
https://hex.pm/packages/amqp/1.4.0-rc.0 is released and it supports 3.8.x. If you experience any issues, let us know!

**Comment by dch** [comment]
Thanks, looks like this Does The Right Thing in mix. Updating all the forks!

But why use 3.8.0 here - rather than 3.8.1 which is what we'd expect?

https://github.com/pma/amqp/blob/master/mix.exs#L38

**Comment by whatyouhide** [comment]
@dch `~> 3.8.0` is a version **requirement**. I says that the `amqp` package supports versions `>= 3.8.0 and < 3.9.0`, so 3.8.1 included.

**Comment by ono** [comment]
I'm planning to release `1.4.0` next week.

**Comment by whatyouhide** [comment]
🥳

**Comment by ono** [comment]
https://hex.pm/packages/amqp/1.4.0 :tada:
