### ISSUE TITLE
Formatting the project

### ISSUE THREAD

**Issue by whatyouhide** [pma/amqp#158]
This is a long shot 😄, but what do you think about running the formatter on this project? It's been used extremely commonly in open-source Elixir projects and has been successful in my personal opinion. AMQP relies on aligning fields and options a lot, we would lose that, but the code would look like any other Elixir code out there that uses the formatter. This is just a "maybe we want this?" issue, I'm not really advocating for it too strongly. Just wanted to bring it up :).

cc @ono

**Comment by whatyouhide** [comment]
Ping @ono? I'm happy to close this if you're not interested, or work on it if you are.

**Comment by ono** [comment]
I'm sorry for not responding quickly - I have been chased with some private stuff.

Yeah, I think it's a good idea. I will find the time and update the project (within couple weeks) so please keep this open. Thanks!
