### ISSUE TITLE
Help me please/

### ISSUE THREAD

**Issue by trojanets** [pma/amqp#159]

**Comment by trojanets** [comment]
As I understud:
C -> S AMQP0091
S->C Start (lalala)
C-S Start.OK (login & pass & other)
S-C tune (1, 0, 0, 0, 0, 0, 12, 0, 10, 0, 30, 7,-1, 0, 2, 0, 0, 0,60,-50) 
And after ?
Heartbeat ?
tune.ok ?
Connection ?
 unsigned char heartbeat[4] = {8,    //frame type
                                      0, 0, //channel (shot = 2 байта)
                                    //   0,0,0,0,
                                      206};
        unsigned char third_frame[20] = {1,            //frame type
                                         0, 0,         //channel (shot = 2 байта)
                                         0, 0, 0, 12,  //Длина = 4 байта
                                         0, 10, 0, 31, // class + method
                                         0, 10,         // sint 10 каналов
                                         0, 0, 32, 0,  // uint(4) = 4096 максимальная длина фрейма
                                         0, 0,         // sint без heartbeat
                                         206};
        unsigned char forth_frame[17] = {1,            //frame type
                                         0, 0,         //channel (shot = 2 байта)
                                         0, 0, 0, 9,  //Длина = 4 байта
                                         0, 10, 0, 40, // class + method
                                         1,'/',         // sstr virtual-host
                                         1,' ',    // Capabilitis ?? sstr
                                         0,         // sint без heartbeat
                                         206};
What i do wrong ?

**Comment by ono** [comment]
This is a repo for Elixir client library. You seem to have posted your question to a wrong place.
