### ISSUE TITLE
unexpected_delivery_and_no_default_consumer under heavy load

### ISSUE THREAD

**Issue by marucjmar** [pma/amqp#168]
Hi,

I am having a strange behavior my consumer, sometimes under heavy load the following problem occurs:
```
=ERROR REPORT==== 10-Jun-2020::11:08:47.187142 ===
** Generic server <0.2973.0> terminating
** Last message in was {consumer_call,
                           {'basic.deliver',
                               <<"amq.ctag-tKMxJqgaeeM-VIaSGUr5NA">>,192,
                               false,<<"queue123">>,<<"my.topic">>},
                           {amqp_msg,
                               {'P_basic',<<"application/json">>,undefined,
                                   undefined,1,undefined,undefined,undefined,
                                   undefined,undefined,undefined,
                                   <<"my.topic">>,undefined,undefined,
                                   undefined},
                               <<123,34,....<MymessageBinary>,125>>}}
** When Server state == {state,amqp_selective_consumer,
                               {state,#{},undefined,#{},none}}
** Reason for termination == 
** unexpected_delivery_and_no_default_consumer 
```

My Consumer code based on [this](https://github.com/pma/amqp#setup-a-consumer-genserver) code. 

Any thoughts?

**Comment by marucjmar** [comment]
Problem has been fixed. It turned out that the problem is caused by the library for sending push notifications(Pigeon). [Code that causes problem](https://github.com/codedge-llc/pigeon/blob/master/lib/pigeon/fcm.ex#L147). When `receive` block has been closed by timeout then the callback message was intercepted by consumer genserver. The consumer genserver could not match this incoming message(by handle_info) and caused a crash. Good practice should be add the default incoming unknown messages handler in genserver like by this: 

```
  def handle_info(_, state) do
    {:noreply, state}
  end
```

I apologize for this issue, it was not directly related to the amqp library.

**Comment by ono** [comment]
@marucjmar sorry i have been unable to respond. no problem. thanks for updating actually. I really like when the issue author updates the outcome/workaround/solution. That helps maintainers :+1:
