### ISSUE TITLE
Exchange.declare doesn't allow to declare custom type

### ISSUE THREAD

**Issue by chilicat** [pma/amqp#17]
We use the [random-exchange plugin](https://github.com/jbrisbin/random-exchange). When I try to declare a exchange with the custom type "x-random"

    Exchange.declare(chan, exchange, :"x-random", durable: false)

I get following error:

```
** (FunctionClauseError) no function clause matching in AMQP.Exchange.declare/4
    (amqp) lib/amqp/exchange.ex:32: AMQP.Exchange.declare(%AMQP.Channel{conn: %AMQP.Connection{pid: #PID<0.286.0>}, pid: #PID<0.297.0>}, "myservice.global", :"x-random", [durable: false])

```

Would it make sense to remove the type restriction in [exchange.ex](https://github.com/pma/amqp/blob/master/lib/amqp/exchange.ex#L33) to make the library more flexible to use ?

**Comment by pma** [comment]
@chilicat Yes, I think it does make sense to remove the guard clause, since it makes a wrong assumption. Care to send a PR?

**Comment by chilicat** [comment]
Here is a PR #18

**Comment by chilicat** [comment]
Hi @pma is the PR good to merge?

**Comment by pma** [comment]
@chilicat I'll make a 0.1.5 release with this change asap

**Comment by jemc** [comment]
@pma - my application needs this fix - can you cut a `0.1.5` release?

**Comment by pma** [comment]
@jemc 0.1.5 is in hex.pm

**Comment by jemc** [comment]
Thanks!
