### ISSUE TITLE
where to find documentation

### ISSUE THREAD

**Issue by Choongkyu** [pma/amqp#193]
Hello. I was reviewing the README, namely this part:
```
When a channel is down and reconnected, you have to make sure your consumer subscribes to a channel again.

See the documentation for AMQP.Application.get_connection/1 and AMQP.Application.get_channel/1 for more details.
```
I was wondering where I might be able to find documentation around this, since I'd like to find an idiomatic way to retry connecting without having connected once before in an environment where docker-compose would run a server container before the rabbitmq container is ready.  Thank you!

**Comment by ono** [comment]
- https://hexdocs.pm/amqp/AMQP.Application.html#get_connection/1
- https://hexdocs.pm/amqp/AMQP.Application.html#get_channel/1

**Comment by ono** [comment]
If you read the README in hex doc, they actually have hyper links: https://hexdocs.pm/amqp/readme.html#configuration

**Comment by ono** [comment]
I just made a little tweak on the sample code there: https://github.com/pma/amqp/commit/20b20a9a18b07402d94404382d6b8a209149c05f
