### ISSUE TITLE
Enabling transactional mode for channels?

### ISSUE THREAD

**Issue by garte** [pma/amqp#196]
I'm currently evaluating persistence guarantees if a RabbitMQ node fails and read about enabling transactional mode in channels.

However, I've not found any way to do this with this library. Am I missing something? Or is this not implemented yet?

(The other topic would be Publisher Confirms, but I guess that's something that's not covered by the AMQP standard?)

**Comment by ono** [comment]
sorry, i didn't notice your message. that's right - `tx` hasn't been implemented yet. no specific reason. PR is welcome if anyone fancies :+1: The approach would be like:

- Create records under core.ex for Tx class
- Implement each functions under newly created AMQP.Tx module

I suppose you can pretty much follow the implementation of `AMQP.Confirm.select/1`.
