### ISSUE TITLE
unexpected_delivery_and_no_default_consumer and abandoned consumers

### ISSUE THREAD

**Issue by karlseguin** [pma/amqp#207]
After trying closing a channel (on an error), we often get" unexpected_delivery_and_no_default_consumer" and end up with "ghost" consumers. We do something like this:

```
rescue  /
  _ ->
    Basic.reject(channel, message.delivery_tag, requeue: requeue)
    Basic.cancel(channel, consumer_tag)
    AMQP.Channel.close(channel)
   {:stop, normal, nil}
```

And we end up with "ghost" channels that have un-acked messages on the rabbitmq side. The simplest way to reproduce this issue reliably:

1 - Run the Consumer from this project's readme (the one that sets up gen_server_test_queue)
2 - Add the following to AMQP.SelectiveConsumer before the existing deliver_to_consumer_or_die/3:
```
defp deliver_to_consumer_or_die(_, {:basic_deliver, _, _}, _) do
  exit(:unexpected_delivery_and_no_default_consumer)
end
```
3 - Send a message to the queue

This is obviously extreme, but it's meant to show what happens when the SelectiveConsumer exits. If you explore the RabbitMQ interface, you should see a pending "ack". If you wait consumer_timeout amount of time (a) rabbitmq will start to log errors about "consumer ack timed out on channel 1" and you'll see in the interface, this "ghost" channel that has an unacked message but no consumers.

I would think that closing the channel would solve this issue, but it doesn't appear to. This very rarely happens, so I'm thinking it's some timing between the message being received, the :DOWN being received and the Channel close being processed on the RabbitMQ side.

**Comment by ono** [comment]
isn't it possible to make sure cleaning up the resource like channel or connection with monitor or by linking? maybe it is useful to add some tips in README?

**Comment by karlseguin** [comment]
@ono I tried that, but it didn't work. I don't remember exactly what happened, it was a long time ago. I somewhat remember it behaved much worse though.

To shutdown the consumer, the flow that appears to work:
1 - Call `Basic.cancel(channel, consumer_tag)`
2 - Reject any subsequent messages
3 - Only once `basic_cancel_ok` is received can the channel be closed and the consumer stopped

For our case, because we have a "base consumer", it involves using the process dictionary a lot (to track if messages should be processed, the channel and the consumer tag)

**Comment by karlseguin** [comment]
The above is 100% necessary in order to cleanly shut down a consumer. I do wish this library provided simple options for handling undeliverable messages, such as a nacking (instead of the fixed behavior of panic'ing).

With the proper handling of shutdown (i.e. handling inflight messages and waiting for basic_cancel_ok) AND with a relatively recent version of rabbitmq, this problem finally appears resolved for us.

Specifically, if you're using quorum queues, these two issues in RabbitMQ itself, now fixed, seem to have resulted in either in-flight messages being sent AFTER basic_cancel_ok, or some other weird behavior that caused problems:
https://github.com/rabbitmq/rabbitmq-server/pull/3746
https://github.com/rabbitmq/rabbitmq-server/pull/3448
