### ISSUE TITLE
Does connections/channels close automatically when connection is severed

### ISSUE THREAD

**Issue by bradleyd** [pma/amqp#21]
Hey,
We are noticing connections still hanging around when amqp consumer dies.  Do we need to explicitly handle that in callbacks?

Thanks!

**Comment by pma** [comment]
@bradleyd You are correct. The channel or connection won't automatically close when a subscriber process dies. Assuming your subscriber in a GenServer, you can use the terminate callback to cleanup and close the channel. Whether you also close the connection or not will depend if you reusing the same connection for other channels (you can open up to 65535 channels in a single TCP connection).

**Comment by edgurgel** [comment]
`terminate` is not necessarily called on a shutdown: http://elixir-lang.org/docs/v1.1/elixir/GenServer.html#c:terminate/2

What I'm doing is: on `init()` link to the connection and the channel. This is not the best solution as it will not allow you to reuse a connection for multiple consumers but at least it's safe to clean up hanging processes. I think this should be fixed upstream (rabbitmq-client)...

**Comment by bradleyd** [comment]
@pma thanks for the response.  We are seeing AWS LB close connections after N time of inactivity.  The connection is closed unexpectedly--hence creating multiple connections everytime supervisor restarts our consumer.

**Comment by bradleyd** [comment]
@edgurgel in our case that would be fine as we only have one consumer

**Comment by bradleyd** [comment]
@pma maybe an example in `README.md` would be nice?

**Comment by chvanikoff** [comment]
@bradleyd with AWS LB you have to enable heartbeat option to prevent connections dropping:
```elixir
{:ok, conn} = AMQP.Connection.open([
  host: config[:host],
  username: config[:username],
  password: config[:password],
  connection_timeout: 2000,
  heartbeat: 30 # <- here it is, in seconds
])
```
