### ISSUE TITLE
Unhandeled Genserver event

### ISSUE THREAD

**Issue by Zaherhs** [pma/amqp#213]
According to the [Genserver Docs](https://hexdocs.pm/elixir/1.6.3/GenServer.html#call/3-timeouts):
> [](https://hexdocs.pm/elixir/1.6.3/GenServer.html#cast/2)timeout is an integer greater than zero which specifies how many milliseconds to wait for a reply, or the atom :infinity to wait indefinitely. The default value is 5000. If no reply is received within the specified time, the function call fails and the caller exits. If the caller catches the failure and continues running, and the server is just late with the reply, it may arrive at any time later into the caller’s message queue. The caller must in this case be prepared for this and discard any such garbage messages that are two-element tuples with a reference as the first element.

This event is not well handled in the library and it is easy to reproduce by:
- Cutting the connection (or maybe supply a non valid RBMQ url) to force reconnection
- ADding in the `AMQP.Application.Connection` module 5 seconds sleep like the following:
```elixir
  def handle_call(:get_connection, _, state) do
    :timer.sleep(5000)

    if state[:connection] && Process.alive?(state[:connection].pid) do
      {:reply, state[:connection], state}
    else
      {:reply, nil, state}
    end
  end
```

When we do that we have the following error:
```elixir
[error] Failed to open AMQP connection (default). Retrying later... 
[error] Failed to open an AMQP channel(amqp_chan). Connection (default) is not ready. 
[error] GenServer :"Elixir.AMQP.Application.Channel::amqp_chan" terminating
** (FunctionClauseError) no function clause matching in AMQP.Application.Channel.handle_info/2
    (amqp 3.1.0) /Users/zaherhs/amqp/lib/amqp/application/channel.ex:120: AMQP.Application.Channel.handle_info({#Reference<0.1678083489.2965110785.199331>, nil}, %{channel: nil, connection: :default, monitor_ref: nil, name: :amqp_chan, retry_interval: 5000})
    (stdlib 3.14.2.2) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.2.2) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.2.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {#Reference<0.1678083489.2965110785.199331>, nil} 
```

The solution is mentioned above in the docs:
> The caller must in this case be prepared for this and discard any such garbage messages that are two-element tuples with a reference as the first element.

**Comment by ono** [comment]
Thanks! It will be addressed with https://github.com/pma/amqp/pull/212
