### ISSUE TITLE
Support for streams

### ISSUE THREAD

**Issue by alfetahe** [pma/amqp#215]
Are there any plans for the streams plugin support?

**Comment by ono** [comment]
Not really.

- The goal of this Elixir library is to provide a thin wrapper for [Erlang library ](https://github.com/rabbitmq/rabbitmq-server/tree/master/deps/amqp_client)
- It looks to be a common approach to have a separate client library for Stream support e.g. [Java](https://github.com/rabbitmq/rabbitmq-stream-java-client) and [Go](https://github.com/rabbitmq/rabbitmq-stream-go-client)

To be honest, I am not familiar with Stream plugin. Maybe best getting the further advice on https://groups.google.com/g/rabbitmq-users .
