### ISSUE TITLE
No feedback when RabbitMQ is unreachable

### ISSUE THREAD

**Issue by oatmealb** [pma/amqp#218]
When providing `AMQP.Connection.open/1` an invalid `:host`, among its other `keyword` options, there's no feedback that the provided host can not be reached. Starting an application merely hangs, with the last log being:

```
[info] Application amqp started on node 'a@node-12324567'
```

Please give any guidance on getting such feedback, that the host can't be reached.

**Comment by ono** [comment]
You can set up connection_timeout option and it is 50 seconds by default.

https://hexdocs.pm/amqp/AMQP.Connection.html#open/2

Can you try setting up shorter time there?
