### ISSUE TITLE
AMQP issue crashes GenServer irrespective of multiple error handlers. 

### ISSUE THREAD

**Issue by Ganarajr** [pma/amqp#222]
Hi Team,
We are facing a peculiar issue with Consumer GenServer.
AMQP.Queue.declare crashes in case of an access to exclusive queue. It does not return an error tuple, instead triggers the terminate(). 
Terminate receives a nested tuple with the reason tuple enclosed in another tuple , due to which it exits abruptly. This leaves the terminal process incomplete and we enter a deadlock and the queue/connection/channel is never closed. When the GenServer restarts, it tries to create a queue but since the previous queue is alive it crashes and is perennially in deadlock.  We have tried even try-catch as well but no avail.

Is there something I am missing here?

Posting my code below:
```

def init(_) do
	  Process.flag(:trap_exit, true)
	  with {:ok, conn} <- Connection.open(broker_host()),
         {:ok, chan} <- Channel.open(conn) do
		       state = %{
		        conn: conn,
		        chan: chan
		       }
           {:ok, state, {:continue, state}}
    else
      e ->
	      Logger.error("Genserver Initialisation failed due to #{inspect(e)}")
	  end
  end

  def handle_continue(%{conn: conn, chan: chan}, state) do
	  Logger.debug("[#{__MODULE__} Initialising...")
		  with {:ok, _} <- AMQP.Queue.declare(chan, @queue, [exclusive: true]),
         :ok <- AMQP.Exchange.direct(chan, @exchange),
         :ok <- AMQP.Queue.bind(chan, @queue, @exchange, routing_key: routing_key),
         :ok <- AMQP.Basic.qos(chan, prefetch_count: 200),
         {:ok, _consumer_tag} <- AMQP.Basic.consume(chan, @queue) do
	          Process.monitor(conn.pid)
            {:noreply, %{conn: conn, chan: chan}}
    else
      {:error, e} ->
		    case AMQP.Channel.close(chan) do
		      :ok ->
		        Logger.info("#{__MODULE__}: Channel is closed")

		
		      {:error, reason} ->
		        Logger.error("#{__MODULE__}: Unable to close RabbitMQ connection. Error: #{inspect reason}")
		    end
		
		    case AMQP.Connection.close(conn) do
		      :ok ->
		        Logger.info("#{__MODULE__}: Connection is closed")
		
		      {:error, reason} ->
		        Logger.error("#{__MODULE__}: Unable to close RabbitMQ connection. Error: #{inspect reason}")
		    end
		    {:stop, nil}
      e ->
		    case AMQP.Channel.close(chan) do
		      :ok ->
		        Logger.info("#{__MODULE__}: Channel is closed")
		
		      {:error, reason} ->
		        Logger.error("#{__MODULE__}: Unable to close RabbitMQ connection. Error: #{inspect reason}")
		    end
		
		    case AMQP.Connection.close(conn) do
		      :ok ->
		        Logger.info("#{__MODULE__}: Connection is closed")
		
		      {:error, reason} ->
		        Logger.error("#{__MODULE__}: Unable to close RabbitMQ connection. Error: #{inspect reason}")
		    end
         Process.send_after(self(), :connect, @reconnect_interval)
        {:stop, nil}
    end
  end


  def terminate(reason, %{conn: conn, chan: chan} = _state) do
    case AMQP.Channel.close(chan) do
      :ok ->
        Logger.info("#{__MODULE__}: Channel is closed")


      {:error, reason} ->
        Logger.error("#{__MODULE__}: Unable to close RabbitMQ connection. Error: #{inspect reason}")
    end

    case AMQP.Connection.close(conn) do
      :ok ->
        Logger.info("#{__MODULE__}: Connection is closed")

      {:error, reason} ->
        Logger.error("#{__MODULE__}: Unable to close RabbitMQ connection. Error: #{inspect reason}")
    end
    Logger.error("#{__MODULE__}: Queue Service Terminating. Error: #{inspect reason}")
    {:stop}
  end 
 ```
``  
  Errors
  Nested reason tuple
  {{:shutdown,
  {:server_initiated_close, 405,
   "RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'server' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration."}},
 {:gen_server, :call,
  [
    #PID<0.800.0>,
    {:call,
     {:"queue.declare", 0, "server", false, false, true, false, false,
      []}, :none, #PID<0.788.0>},
    70000
  ]}}
 `` 

  Error message
  `[error] GenServer Queue.Consumer terminating
** (stop) exited in: :gen_server.call(#PID<0.786.0>, {:close, 200, "Goodbye"}, 70000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib 3.17.2.1) gen_server.erl:247: :gen_server.call/3
    (amqp 3.2.0) lib/amqp/channel.ex:30: AMQP.Channel.close/1
    (server 2.39.0) lib/server/queue/consumer.ex:226: Queue.Consumer.terminate/2
    (stdlib 3.17.2.1) gen_server.erl:733: :gen_server.try_terminate/3
    (stdlib 3.17.2.1) gen_server.erl:918: :gen_server.terminate/10
    (stdlib 3.17.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, %{chan: %AMQP.Channel{conn: %AMQP.Connection{pid: #PID<0.777.0>}, pid: #PID<0.786.0>, custom_consumer: {AMQP.DirectConsumer, {#PID<0.774.0>, [ignore_consumer_down: [:normal, :shutdown]]}}}, conn: %AMQP.Connection{pid: #PID<0.777.0>}}}
State: %{chan: %AMQP.Channel{conn: %AMQP.Connection{pid: #PID<0.777.0>}, pid: #PID<0.786.0>, custom_consumer: {AMQP.DirectConsumer, {#PID<0.774.0>, [ignore_consumer_down: [:normal, :shutdown]]}}}, conn: %AMQP.Connection{pid: `#PID<0.777.0>}}`

**Comment by ono** [comment]
Hi. Unfortunately, it is how the upstream library (amqp_client) works. To avoid the deadlock, what I can suggest is to isolate the declare logic and conn/channel management from consume GenServer and handle the termination there.
