### ISSUE TITLE
websocket support

### ISSUE THREAD

**Issue by drselump14** [pma/amqp#223]
Hi guys, thanks for making this awesome library.
I wonder if there is any plan to implement the websocket support?
Any hint how to start ?

any help would be appreciated?

**Comment by ono** [comment]
Hi @drselump14. Thanks for the message and kind words!

RabbitMQ doesn't support WebSocket. I would suggest to handle it in the different layer. For example, you can handle WebSocket communication in a Phoenix application and relay messages between RabbitMQ there.

I hope it helps!

**Comment by drselump14** [comment]
It does support websocket connection by using the plugin (https://www.rabbitmq.com/web-mqtt.html).
Although, I just realized that the protocol is mqtt not amqp

**Comment by ono** [comment]
Yeah, if you want to write a library for the plug-in, I would suggest to create a new library.
