### ISSUE TITLE
Can't send json message

### ISSUE THREAD

**Issue by nazipov** [pma/amqp#23]
When I try publish json message, I get `FunctionClauseError` error. AMQP version is 0.1.4. Poison version is 1.4.0

```
iex(1)> {:ok, conn} = AMQP.Connection.open
{:ok, %AMQP.Connection{pid: #PID<0.364.0>}}
iex(2)> {:ok, chan} = AMQP.Channel.open(conn)
{:ok,
 %AMQP.Channel{conn: %AMQP.Connection{pid: #PID<0.364.0>}, pid: #PID<0.376.0>}}
iex(3)> AMQP.Queue.declare chan, "test_queue"
{:ok, %{consumer_count: 0, message_count: 0, queue: "test_queue"}}
iex(4)> AMQP.Exchange.declare chan, "test_exchange"
:ok
iex(5)> AMQP.Queue.bind chan, "test_queue", "test_exchange"
:ok
iex(6)> AMQP.Basic.publish(chan, "test_exchange", "", Poison.encode(%{ name: "S" }), [content_type: "application/json"])
:ok
iex(7)>
23:51:45.669 [error] Process #PID<0.377.0> raised an exception
** (FunctionClauseError) no function clause matching in :lists.reverse/1
    (stdlib) lists.erl:146: :lists.reverse({:ok, "{\"name\":\"S\"}"})
    (rabbit_common) src/rabbit_binary_generator.erl:84: :rabbit_binary_generator.build_content_frames/3
    (rabbit_common) src/rabbit_binary_generator.erl:73: :rabbit_binary_generator.build_simple_content_frames/4
    (rabbit_common) src/rabbit_writer.erl:312: :rabbit_writer.assemble_frames/5
    (rabbit_common) src/rabbit_writer.erl:342: :rabbit_writer.internal_send_command_async/3
    (rabbit_common) src/rabbit_writer.erl:210: :rabbit_writer.handle_message/3
    (rabbit_common) src/rabbit_writer.erl:194: :rabbit_writer.mainloop1/2
    (rabbit_common) src/rabbit_writer.erl:185: :rabbit_writer.mainloop/2
```

**Comment by nazipov** [comment]
It's my mistake! Sorry

```
iex(7)> {:ok, m} = Poison.encode(%{ name: "S" })
{:ok, "{\"name\":\"S\"}"}
iex(8)> AMQP.Basic.publish(chan, "test_exchange", "", m, [content_type: "application/json"])
:ok
```

**Comment by pma** [comment]
Hi,

The 4th argument of AMQP.Basic.publish must be a binary and Poison.encode/1
returns a tuple {:ok, iodata}. You can use Poison.encode!/1 (which returns
a binary or raises on error).

On Mon, Mar 28, 2016 at 10:02 PM, Almaz Nazipov <notifications@github.com>
wrote:

> When I try publish json message, I get FunctionClauseError error. AMQP
> version is 0.1.4. Poison version is 1.4.0
>
> iex(1)> {:ok, conn} = AMQP.Connection.open
> {:ok, %AMQP.Connection{pid: #PID<0.364.0>}}
> iex(2)> {:ok, chan} = AMQP.Channel.open(conn)
> {:ok,
>  %AMQP.Channel{conn: %AMQP.Connection{pid: #PID<0.364.0>}, pid: #PID<0.376.0>}}
> iex(3)> AMQP.Queue.declare chan, "test_queue"
> {:ok, %{consumer_count: 0, message_count: 0, queue: "test_queue"}}
> iex(4)> AMQP.Exchange.declare chan, "test_exchange"
> :ok
> iex(5)> AMQP.Queue.bind chan, "test_queue", "test_exchange"
> :ok
> iex(6)> AMQP.Basic.publish(chan, "test_exchange", "", Poison.encode(%{ name: "S" }), [content_type: "application/json"])
> :ok
> iex(7)>
> 23:51:45.669 [error] Process #PID<0.377.0> raised an exception
> ** (FunctionClauseError) no function clause matching in :lists.reverse/1
>     (stdlib) lists.erl:146: :lists.reverse({:ok, "{\"name\":\"S\"}"})
>     (rabbit_common) src/rabbit_binary_generator.erl:84: :rabbit_binary_generator.build_content_frames/3
>     (rabbit_common) src/rabbit_binary_generator.erl:73: :rabbit_binary_generator.build_simple_content_frames/4
>     (rabbit_common) src/rabbit_writer.erl:312: :rabbit_writer.assemble_frames/5
>     (rabbit_common) src/rabbit_writer.erl:342: :rabbit_writer.internal_send_command_async/3
>     (rabbit_common) src/rabbit_writer.erl:210: :rabbit_writer.handle_message/3
>     (rabbit_common) src/rabbit_writer.erl:194: :rabbit_writer.mainloop1/2
>     (rabbit_common) src/rabbit_writer.erl:185: :rabbit_writer.mainloop/2
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pma/amqp/issues/23>
>



-- 
Paulo Almeida
paulo.almeida@timeboxed.co.ao
www.timeboxed.co.ao
T.: (+244) 925721924
