### ISSUE TITLE
The library is not working with OTP 27 (But there is a workaround)

### ISSUE THREAD

**Issue by ono** [pma/amqp#231]
This is a known issue with RabbitMQ - https://www.rabbitmq.com/blog/2024/05/23/erlang27-support and this library is depending on their Erlang client library. We are waiting for them to deliver a fix.

We also requested RabbitMQ team to continue to support amqp_client: https://github.com/rabbitmq/rabbitmq-server/issues/11593

**UPDATE on July 4, 2024**

I found a workaround. rabbit_common 3.13.4 can be compiled with OTP 27. According to the RabbitMQ team, there has been no change on amqp_client since 3.12.x. Therefore you can use OTP 27 by overriding rabbit_common version in mix.exs like below.

```elixir
  defp deps do
    [
      {:amqp, "~> 3.3"},
      {:amqp_client, "~> 3.12"},
      {:rabbit_common, "~> 3.13.4", override: true},
      ...
```

I ran unit tests with it and all passed.

We can't officially support it but I personally think the risk is low. The performance issue with OTP 27 seems to be server related.

**Comment by epinault** [comment]
has this been released?

**Comment by justincy** [comment]
I also receive the error about conflicting ranch versions. It's caused by [this PR](https://github.com/rabbitmq/rabbitmq-server/pull/11039) in rabbit was was [backported into 3.13.x](https://github.com/rabbitmq/rabbitmq-server/pull/11040).

@epinault You might try adding `{:ranch, "~> 1.8.0", override: true}`. It seems to work for me.

**Comment by epinault** [comment]
unfortunately, seems like i am stuck because esaml also depends on cowboy and cause a conflict dependency too now

**Comment by ono** [comment]
4.0.0 is out and it supports OTP 27. The client is compatible with both RabbitMQ 3.x and 4.x. Please note that the RabbitMQ team has reported some performance issues with OTP 27.

https://www.rabbitmq.com/blog/2024/05/23/erlang27-support

This might not be relevant to the client side in most cases, but we recommend you monitor carefully.

I am not sure if the dependency issue has also been solved. At least, it doesn't seem to be directly related to the main topic. Please be aware that the dependency issue with amqp_client and rabbit_common is not something we can address here (this library has no control). You might need to report it to RabbitMQ team.
