### ISSUE TITLE
Suspend Channe or Connection

### ISSUE THREAD

**Issue by mvbaffa** [pma/amqp#40]
Hi,

I need to suspend or stop temporarily receiving messages from my Queue. I close the Channel like this

`Channel.close(chan)`

When try to reopen the channel, not the connection, at start receiving again the messages from the Queue, I call 

`Channel.open(chan)`

But I receive the error message 

> no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started

How can I do this ?

Thanks

**Comment by pma** [comment]
@mvbaffa Assuming it's not a typo, you need to pass an open Connection to Channel.open/1, to the channel you just closed. When you close a channel, the underlying process representing the channel is terminated.

An alternative to closing the channel is calling Basic.cancel. The server will stop sending additional messages to the consumer process.

**Comment by mvbaffa** [comment]
How can I find the Basic.Cancel signature ?

After supending witrh Basic.Cancel how can I resume receiving messages ?

**Comment by pma** [comment]
@mvbaffa You can do `h AMQP.Basic.cancel` in the iex shell or take a look at the implementation: https://github.com/pma/amqp/blob/master/lib/amqp/basic.ex#L304

To resume, simply register as a consumer using `AMQP.Basic.consume` (https://github.com/pma/amqp/blob/master/lib/amqp/basic.ex#L208)

**Comment by mvbaffa** [comment]
Thanks

I will check it out
