### ISSUE TITLE
expiration option not working

### ISSUE THREAD

**Issue by laibulle** [pma/amqp#42]
Hello, 

when I use the expiration option, the message is not sent to my queue. I checked if it was not instantly expired but it is not. When I comment the expiration option it is working. When I create a message in the rabbitmq web interface, it works as expected.

```
def create_queue(req, chan) do
    {:ok, format} = Timex.format(req.launch_at, "%Y%m%d", :strftime)
    queue = "requests_#{format}"
    :ok = Exchange.direct(chan, @exchange, durable: true)
    {:ok, _} = Queue.declare(chan, @ready_queue, durable: true) # Declare the dead letter queue target
    {:ok, _} = Queue.declare(chan, queue, durable: true)
    :ok = Queue.bind(chan, @ready_queue, @exchange, routing_key: "ready")
    {:ok,  queue }
end

def publish(req) do
    {:ok, conn} = Connection.open(@conn_str)
    {:ok, chan} = Channel.open(conn)
    {:ok, queue} = create_queue(req, chan)

    :ok = Basic.publish(
      chan,
      "",
      queue,
      req.id,
      persistent: true,
      mandatory: true,
      headers: [
        {"x-dead-letter-exchange", :longstr, @exchange},
        {"x-dead-letter-routing-key", :longstr, "ready"}
      ],
      expiration: 10000
    )

    :ok = Connection.close(conn)
  end
```

<img width="954" alt="screen shot 2016-10-25 at 01 00 39" src="https://cloud.githubusercontent.com/assets/2327626/19667223/f29e02c2-9a4f-11e6-9248-e2055c1de9ec.png">

Am I missing something ?

Best regards

**Comment by laibulle** [comment]
Ok, 

I found the solution while ready RabbitMQ doc. 

> Since the expiration field must be a string, the broker will (only) accept the string representation of the number.

So the code works changing the int to string:

`
expiration: "10000"
`

**Comment by rafaeljesus** [comment]
@laibulle can you close the issue mate?

**Comment by laibulle** [comment]
Yes, 

thanks
