### ISSUE TITLE
Send a message including type

### ISSUE THREAD

**Issue by mvbaffa** [pma/amqp#43]
Hi,

I need to send a message setting the type field.
How can I do it. Can I use the BasicPublish ?

Thanks in advance

**Comment by ono** [comment]
Hi @mvbaffa. Thanks for using the library.

You might have already figured but yes you can set message type with `Basic.publish/5`. Please check the API documentation for the detail: https://hexdocs.pm/amqp/0.2.0-pre.1/AMQP.Basic.html#publish/5
