### ISSUE TITLE
Document not available in hexdocs.pm

### ISSUE THREAD

**Issue by raysegantii** [pma/amqp#45]
It's broken for the moment: https://hexdocs.pm/amqp/

**Comment by ono** [comment]
Hey @raysegantii. Thanks for reporting 👍

Fixed the doc main page and republished.

- https://hexdocs.pm/amqp/
- https://hexdocs.pm/amqp/0.2.0-pre.1/

Both should work now. In case you still see the error, try removing the page cache from your browser.
