### ISSUE TITLE
Update amqp cliento to 3.6.2

### ISSUE THREAD

**Issue by mrkaspa** [pma/amqp#47]
Check this thread https://github.com/jbrisbin/amqp_client/issues/36#issuecomment-266859776 I have to do this to make this library works

{:amqp, "0.1.5"},
{:amqp_client, git: "https://github.com/jbrisbin/amqp_client.git", tag: "rabbitmq-3.6.2", override: true},

But I need to release a hex library but I can't because I'm overriding the dependency

**Comment by arjan** [comment]
:+1:

**Comment by ono** [comment]
I'm happy to help testing if needed and work on implications if there are any. Ping me if any helps needed. It'll be great if this is solved soon.

**Comment by mingchuno** [comment]
@pma @ono agree, this issue should be the first priority.

**Comment by ono** [comment]
We have just merged https://github.com/pma/amqp/pull/51 and now amqp supports OTP 19 :v:

Please change the version of amqp to `0.2.0-pre.1` and run `mix deps.update amqp && mix deps.get` (you need to run `mix deps.get` to get `rabbit_common`). Let us know if you experience any issues.
