### ISSUE TITLE
`rabbit_common` dependency doesn't compile on newer rebar versions

### ISSUE THREAD

**Issue by mschae** [pma/amqp#6]
On newer versions of rebar (tested with 2.5.1) the dependency `rabbit_common` doesn't compile.

@mobileoverlord has found a rabbit_common version from @d0rc that seems to be fixing this.

See here for the error: https://travis-ci.org/mschae/rebar_problem/builds/53253499#L109-L116
And here for a fixed version: https://travis-ci.org/mschae/rebar_problem/builds/56574002

The trick is to use `{:amqp_client, github: "d0rc/amqp_client", override: true}` as the `amqp_client` version: https://github.com/mschae/rebar_problem/compare/alternative_rebar_common?expand=0

**Comment by pma** [comment]
@mschae @mobileoverlord Thanks for reporting this.

`d0rc/amqp_client` compiles beause it has the the flag `warnings_as_errors` commented in rebar.conf. In  jbrisbin/amqp_client`, which is the one used to build the community hex package, the flag is on.

I actually submitted a couple of PR's to jbrisbin's repo to get rid of the warnings. I'm still not sure what changed in the latest rebar to cause the warning about the behaviour gen_server2 being undefined. I will look into this and update the amqp_client hex package.

A similar issue, with the supervisor2 behaviour was discussed in the RabbitMQ forum (https://groups.google.com/forum/#!topic/rabbitmq-users/ThCiHBOXMlE). It was later fixed upstream, so I'll check if they already handled the gen_server2 behaviour warning.

**Comment by pma** [comment]
@mschae 
I updated to rebar 2.5.1 but so far was unable to reproduce the problem.

Here's my log after compiling your mschae/rebar_problem: https://gist.github.com/pma/bff0f180b32d28d092b4

I noticed that in the failed Travis build log, gen_server2.erl should have been the first file to be compiled, but it's not. This is enforced in rebar.conf by https://github.com/jbrisbin/rabbit_common/blob/master/rebar.config#L2.

**Comment by pma** [comment]
@mschae 
Could be related to this issue in rebar (https://github.com/rebar/rebar/pull/445). As I understand the issue can cause rebar to discard the file compilation order set by `erl_first_files` in rebar.config and use the order of the filesystem.

When using container-based infrastructure for the Travis build, the file order of the filesystem could be different. Would explain why I'm not able to reproduce this locally and why my previous travis.yml did not fail (https://github.com/pma/amqp/commit/fe10f9f8bfec05ae92aa56f560542008a9445992).
