### ISSUE TITLE
Direct connections to broker should be supported

### ISSUE THREAD

**Issue by binarin** [pma/amqp#60]
I'm currently trying to implement RabbitMQ plugin in Elixir, and having a direct connection is an essential piece of functionality.

I see 2 possible ways to handle this:
1) Add new function `AMQP.Connection.open_direct/1`, which will accept completely different set of options compared to `open/1`
2) Add 2 more clauses to `open/1` which will be using `is_record` guard to check for directly supplied `amqp_params_network` and `amqp_params_direct` records and just use them without changing.

WDYT? What option is acceptable? I'll be more than happy to make a PR on this issue.

**Comment by ono** [comment]
I think that we want to hide record from public functions as much as possible so I want to avoid option 2.

Instead of `open_direct/1`, I would like to introduce `open/2` e.g. (I omit guards here)

```elixir
def open(options), do: open(:network, options)

def open(:network, options) do
  ...
end

def open(:direct, options) do
  ...
end
```

Yeah, PR will be appreciated 👍 

@pma let us know if you have anything to add or any concerns over `open/2`.

**Comment by ono** [comment]
Correction 📝 Forget about `open/2`.

@binarin Let's go for `open_direct/1` for now. That way, we can keep the API documentation separate for each options. Since number of options is big, it will help users to avoid confusion.

**Comment by pma** [comment]
@ono @binarin I agree that Records should be an internal representation and not exposed in the public API. 👍  to adding `open_direct/1`.
