### ISSUE TITLE
OTP Release 20.0 Support

### ISSUE THREAD

**Issue by ono** [pma/amqp#66]
Confirmed [all tests passed with OTP 20.0](https://travis-ci.org/pma/amqp/builds/247601043) and added the environment to [Travis CI config](https://github.com/pma/amqp/blob/master/.travis.yml#L11-L12). However we recommend you to wait until RabbitMQ team release [Erlang client](https://github.com/rabbitmq/rabbitmq-erlang-client) version `3.6.11` which will officially support OTP release 20.0.

- https://github.com/rabbitmq/rabbitmq-erlang-client/releases
- https://github.com/rabbitmq/rabbitmq-server/releases

**Comment by johanrhodin** [comment]
3.6.11 has been released.

**Comment by ono** [comment]
Tested and confirmed things working mostly. However I encountered [this issue](https://github.com/pma/amqp/issues/73). You can update to OTP 20 by updating amqp_client if you don't use `Connection.open_direct` API.
