### ISSUE TITLE
Rename to something more descriptive and less official

### ISSUE THREAD

**Issue by dantswain** [pma/amqp#7]
I realize it's a stretch to hope for a change at this point, but this library has an unfortunate name.  "AMQP" is the name of the protocol, not a client library.  Further, the name could give a false sense of official-ness, which could be construed as unethical and may or may not cause issues down the road.

This is not a comment on the quality of the library, which I believe to be good.  If anything, I want to enhance the usefulness and longevity of this project.

Like I said, I realize it's a stretch at this point.

**Comment by pma** [comment]
@dantswain For now I will include a disclaimer in the Readme mentioning this is a community supported library and not an official client (afaik only the .Net, Java and Erlang clients are officially supported).

When naming this library, I just went with the easy approach and used the name of equivalent libs in other languages (there are at least Python, Go and Ruby clients named amqp).

Feel free to make a few new name suggestions to be considered before releasing 1.0.

**Comment by pma** [comment]
Closed by https://github.com/pma/amqp/commit/ba95d4a8727ee3d04c225abe08fb2225180af271

**Comment by Mehonoshin** [comment]
Probably it could be named ex_amqp, or even ex_rabbitmq_client.
Actually RabbitMQ is based on AMQP protocol, but has some specific extensions.
So it makes sense to clarify this moment.
