### ISSUE TITLE
Connection.open_direct is not working with latest amqp_client

### ISSUE THREAD

**Issue by ono** [pma/amqp#73]
[The test](https://github.com/pma/amqp/blob/master/test/connection_test.exs#L18) fails with the amqp_client 3.6.11 on local.

**Comment by ono** [comment]
@binarin I haven't look into the issue properly but wonder if you can take a look as you wrote [the PR](https://github.com/pma/amqp/pull/61). You will be able to reproduce the issue by running `mix test` with master branch on your local. Thanks!

**Comment by binarin** [comment]
I'll try to investigate it this week. But looks like there is some problem in `amqp_client` from RabbitMQ itself.

**Comment by ono** [comment]
Thanks Alexey!

**Comment by ono** [comment]
Remove open_direct from master for time being. Once it's sorted out on rabbit_client, we can revert https://github.com/pma/amqp/commit/836978fb677b55709a6e7de52bafb7eb65d03e84 .

**Comment by ono** [comment]
This appears to be addressed on 3.7.15  🙌

**Comment by ono** [comment]
I don't think there is high demand. Open for PR to support this but closing this for now.
