### ISSUE TITLE
Feature: Typespecs 

### ISSUE THREAD

**Issue by lswith** [pma/amqp#76]
It would be extremely helpful to have Elixir typespecs for the core Erlang Records. This would help with creating a generic AMQP GenServer Behaviour.

**Comment by ono** [comment]
Can you be more specific about it? Do you mean you want to see `@type :p_basic :: record(:p_basic, ...)` in https://github.com/pma/amqp/blob/master/lib/amqp/core.ex ?

Can you also show me an example code that explains how it would help creating a generic AMQP GenServer behaviour?

Thanks!

**Comment by ono** [comment]
Closing now. Please reopen with answers for my questions above :point_up:
