### ISSUE TITLE
** (Mix) Could not start application recon: could not find application file: recon.app

### ISSUE THREAD

**Issue by mvalitov** [pma/amqp#78]
a very strange error, I used the same version in another project, and it's all good. Now, when I create a new project on the same machine and add the amqp library, when I try to start the server I get this error.

```
[info] Application syntax_tools exited: :stopped
[info] Application xmerl exited: :stopped
[info] Application cowboy exited: :stopped
[info] Application cowlib exited: :stopped
[info] Application ranch exited: :stopped
[info] Application runtime_tools exited: :stopped
 
=INFO REPORT==== 30-Nov-2017::19:05:28 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application recon: could not find application file: recon.app
```

deps
```
    [
      {:phoenix, "~> 1.3.0"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.2"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.10"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.11"},
      {:cowboy, "~> 1.0"},
      {:amqp, "~> 1.0.0-pre.2"}
    ]
```

The other old project runs without errors

**Comment by mvalitov** [comment]
as I was told, after adding recon to deps, everything worked

**Comment by pma** [comment]
@mvalitov It seems `recon` was added as a dependency of rabbit_common v3.6.13. You could lock your mix.exs to an earlier version of amqp_client and rabbit_common, since amqp will work just as well.

```
{:rabbit_common, "3.6.12", override: true},
{:amqp_client, "3.6.12", override: true},
```

But anyway it's strange why recon is not being pulled, as it is a direct dependency of rabbit_common (earliest versions). Could be an issue with the rabbit_common packaging.

**Comment by ono** [comment]
Hmm, maybe we should add recon to dependency? I can't remember but is this why we add `rabbit_common` to dependencies although it is a direct dependency of `amqp_client`?

**Comment by pma** [comment]
@ono Yes, `rabbit_common` had the exact same issue, reason why it was included as a direct dependency. I'll report this to the Hex.pm and RabbitMQ projects, could be something with the erlang.mk/hex tooling.
