### ISSUE TITLE
Unable to change the queue mode

### ISSUE THREAD

**Issue by msmykowski** [pma/amqp#86]
I expected to be able to change the queue mode from lazy to default with --

`Queue.declare(chan, @queue, durable: true,
                                arguments: [{"x-dead-letter-exchange", :longstr, ""},
                                            {"x-dead-letter-routing-key", :longstr, @queue_error},
                                            {"x-queue-mode", :longstr, "default"},
                                            {"x-max-priority", :short, 10}])`

but this does not seem to work. The queue will still display `queue-mode: lazy`

I am running on rabbit 3.7.3 and Erlang 20.1.

**Comment by hoodsuphopeshigh** [comment]
https://hexdocs.pm/amqp/AMQP.Queue.html#declare/3

The docs specify that the options part should be a keyword list, so it'd be worth trying the same function call as:

```elixir
Queue.declare(chan, @queue, [durable: true, arguments: [{"x-dead-letter-exchange", :longstr, ""}, {"x-dead-letter-routing-key", :longstr, @queue_error}, {"x-queue-mode", :longstr, "default"}, {"x-max-priority", :short, 10}]])
```

**Comment by ono** [comment]
I don't think you can update the queue with declare. This library can't do anything about it.

http://www.rabbitmq.com/amqp-0-9-1-reference.html#queue.declare

> This method creates or checks a queue. When creating a new queue the client can specify various properties that control the durability of the queue and its contents, and the level of sharing for the queue.

You can see more information [here](https://www.rabbitmq.com/lazy-queues.html).

> If queue mode was configured via a policy, it is possible to change it at runtime without the need of deleting and re-declaring the queue. 

This implies that it is not possible to change the queue mode if it was configured via declare.
