### ISSUE TITLE
Amqp uses old version recon

### ISSUE THREAD

**Issue by DmitryKK** [pma/amqp#98]
Hello. I cant install amqp with [observer_cli](https://github.com/zhongwencool/observer_cli) together because they uses different versions of recon. 

```
Failed to use "recon" (versions 2.3.0 to 2.3.4) because
  amqp (version 1.0.3) requires ~> 2.3.2
  observer_cli (version 1.3.1) requires 2.3.5
  mix.exs specifies ~> 2.3


Failed to use "recon" (version 2.3.5) because
  amqp (version 1.0.3) requires ~> 2.3.2
  observer_cli (version 1.3.1) requires 2.3.5
  rabbit_common (version 3.7.5) requires 2.3.2
  mix.exs specifies ~> 2.3
```

I suggest you to update dependencies

**Comment by whatyouhide** [comment]
Just chiming in to say that a library (such as amqp) should likely not depend on a production inspection tool like recon in the first place.

**Comment by DmitryKK** [comment]
@whatyouhide I agree with you. But recon is used amqp, rabbit_common and observer_cli :(

**Comment by ono** [comment]
Closing the issue for now because we can't really solve this as long as we depend on rabbit_common. If anyone has got a solution, feel free to reopen with it.
